# Generated by Django 4.2.6 on 2023-10-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realestatelistings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestatelisting",
            name="photo",
            field=models.CharField(max_length=5000),
        ),
    ]
