# Generated by Django 4.2.6 on 2023-10-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realestatelistings", "0002_alter_realestatelisting_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestatelisting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="realestatelisting",
            name="features",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="realestatelisting",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="realestatelisting",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="realestatelisting",
            name="property_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="realestatelisting",
            name="publication_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="realestatelisting",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("sold", "Sold"),
                    ("pending", "Pending"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="realestatelisting",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
