# Generated by Django 4.2.6 on 2023-10-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realestatelistings", "0003_alter_realestatelisting_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestatelisting",
            name="slug",
        ),
        migrations.AlterField(
            model_name="realestatelisting",
            name="photo",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
