# Generated by Django 4.2.6 on 2023-10-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("realestatelistings", "0004_remove_realestatelisting_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("deed", "Deed"),
                            ("title insurance policy", "Title Insurance Policy"),
                            ("property tax records", "Property Tax Records"),
                            ("survey", "Survey"),
                            ("mortgage documents", "Mortgage Documents"),
                            (
                                "homeowners association (hoa) arecords",
                                "Homeowners Association (HOA) Records",
                            ),
                            ("utility bills", "Utility Bills"),
                            ("estate planning documents", "Estate Planning Documents"),
                            ("affidavit of title", "Affidavit of Title"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_documents",
                        to="realestatelistings.realestatelisting",
                    ),
                ),
            ],
        ),
    ]
