# Generated by Django 4.2.6 on 2023-10-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realestatelistings", "0005_extradocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="extradocument",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="extra-document/"),
        ),
    ]
