# Generated by Django 4.2.6 on 2023-10-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("realestatelistings", "0006_extradocument_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extradocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deed", "Deed"),
                    ("title insurance policy", "Title Insurance Policy"),
                    ("property tax records", "Property Tax Records"),
                    ("survey", "Survey"),
                    ("mortgage documents", "Mortgage Documents"),
                    (
                        "homeowners association (hoa) records",
                        "Homeowners Association (HOA) Records",
                    ),
                    ("utility bills", "Utility Bills"),
                    ("estate planning documents", "Estate Planning Documents"),
                    ("affidavit of title", "Affidavit of Title"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TokenDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inital_token_price", models.FloatField(blank=True, null=True)),
                ("is_token_fractional", models.BooleanField(default=False)),
                ("fractions", models.IntegerField(blank=True, null=True)),
                (
                    "listing",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_detail",
                        to="realestatelistings.realestatelisting",
                    ),
                ),
            ],
        ),
    ]
