# Generated by Django 4.2.6 on 2023-10-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("realestatelistings", "0001_initial"),
        ("crowdfundings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crowdfundingcampaign",
            name="realestatelisting",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="realestatelistings.realestatelisting",
            ),
        ),
    ]
