# Generated by Django 4.2.6 on 2023-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crowdfundings", "0003_crowdfundingcampaign_realestatelisting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crowdfundingcampaign",
            name="categories",
        ),
        migrations.AddField(
            model_name="contribution",
            name="no_of_token",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
