# Generated by Django 4.2.6 on 2023-10-28 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crowdfundings", "0004_remove_crowdfundingcampaign_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crowdfundingcampaign",
            name="organizer_profile",
        ),
        migrations.AlterField(
            model_name="crowdfundingcampaign",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crowdfunding_campaign",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
