# Generated by Django 4.2.6 on 2023-10-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crowdfundings",
            "0005_remove_crowdfundingcampaign_organizer_profile_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="crowdfundingcampaign",
            name="funding_target",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="crowdfundingcampaign",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
